### PR TITLE
Remove Travis

### PR DESCRIPTION
**Pull request by thewilkybarkid**
As we're now using Alfred.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
This was forked out before the `Jenkinsfile` was in `develop`, so Alfred said:
`
    Checking pull request #10
    (not from a trusted source)
    Job name: PR-10
      ‘Jenkinsfile’ does not exist in this pull request
    Does not meet criteria
`
and didn't build it. There are no code changes so no big deal.

**Comment by giorgiosironi** [comment]
Still :+1:

**Comment by thewilkybarkid** [comment]
Looks like the status image isn't working.

**Comment by giorgiosironi** [comment]
Testing:
[http://ci--alfred.elifesciences.org/buildStatus/icon?job=test-api-dummy]

**Comment by giorgiosironi** [comment]
Done it, check previous comment for a test.

**Pull request merged**
