### PR TITLE
Article 26231 breaks in v2

### PR DESCRIPTION
**Pull request by giorgiosironi**
Makes https://github.com/elifesciences/search/pull/179 fail.

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
What's happening is that there are duplicate keys, PHPUnit presumably uses `iterator_to_array()` at some point which means only the last key value is used.

**Comment by giorgiosironi** [comment]
1 GB of memory in `api-dummy--ci` gets saturated:
```
mmap() failed: [12] Cannot allocate memory
```
Happens around
```
test\eLife\DummyApi\SmokeTest::it_returns_valid_responses with data set "/search?start-date=2017-01-01&end-date=2017-01-01" 
(Symfony\Component\HttpFoundation\Request Object (...), 'application/vnd.elife.search+...sion=1')
```
but is really linear with the number of tests executed.

**Comment by thewilkybarkid** [comment]
The real articles in seem to use a _lot_ of memory to validate, might be a leak somewhere.

**Comment by giorgiosironi** [comment]
Trying to trace the memory usage gets to 18GB of trace after 14 tests, not viable to do the whole suite.

**Comment by giorgiosironi** [comment]
Works very well, good catch; memory usage is down from 600 to 20 MB.

**Comment by giorgiosironi** [comment]
:+1: (manual approval as I have opened the PR and can't click the `Approve` button)

**Pull request merged**
