### PR TITLE
Remove Medium API

### PR DESCRIPTION
**Pull request by thewilkybarkid**
https://github.com/elifesciences/issues/issues/4291

### CODE REVIEW

**Comment by lsh-0** [comment]
@thewilkybarkid , it's been a while since you worked on this, but do you recall if there was any further work to be done? (it's marked as a draft)

**Comment by thewilkybarkid** [comment]
Probably awaiting the update version of `elife/api` with the schema removes.

**Comment by nlisgo** [comment]
There is one change needed. Once the api-raml changes have been merged in we need to run `composer update elife/api` to update the `composer.lock` and bring in those updates.

**Comment by lsh-0** [comment]
cheers, @nlisgo . I've reverted the pin back to `dev-master` and ran `composer update elife/api`

if that was ok, please re-approve

**Comment by nlisgo** [comment]
This has been merged in now.

**Pull request closed without merging**
